# Generated by Django 5.0.11 on 2025-01-27 07:54

import HrAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0005_employee_image_address_attendance_personal_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Personal Detail',
                'verbose_name_plural': 'Personal Details',
            },
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[HrAdmin.models.validate_birthday]),
        ),
    ]
