# Generated by Django 5.0.11 on 2025-01-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0006_personaldetail_alter_personal_detail_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
