# Generated by Django 5.0.11 on 2025-01-30 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0011_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('purchased_date', models.DateField()),
                ('purchase_from', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('warranty', models.IntegerField(help_text='Warranty period in months')),
                ('asset_user', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='HrAdmin.category')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=100)),
                ('primary_relationship', models.CharField(max_length=50)),
                ('primary_phone_no_1', models.CharField(max_length=15)),
                ('primary_phone_no_2', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_phone_no_1', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_phone_no_2', models.CharField(blank=True, max_length=15, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='HrAdmin.employee')),
            ],
        ),
    ]
