# Generated by Django 5.0.11 on 2025-01-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0013_holiday_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_asset', to='HrAdmin.employee'),
        ),
    ]
