# Generated by Django 5.0.11 on 2025-01-30 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0014_asset_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
