# Generated by Django 5.0.11 on 2025-01-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0015_asset_assigned_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Holiday', 'verbose_name_plural': 'Holiday'},
        ),
    ]
