# Generated by Django 5.0.11 on 2025-01-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HrAdmin', '0016_alter_holiday_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='status',
        ),
    ]
